version: '3.7'
services:
  dev:
    container_name: new-container-name
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "/app/start.sh"]
    # ports:
    #   - 8080:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
